import Link from "next/link";
import { ShieldAlert, ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 flex flex-col font-sans">
      <header className="px-8 py-6 flex items-center justify-between border-b border-white/10 backdrop-blur-md sticky top-0 z-50">
        <div className="flex items-center gap-4">
          <Link href="/" className="hover:text-blue-400 transition-colors">
            <ArrowLeft className="w-6 h-6" />
          </Link>
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-6 h-6 text-blue-500" />
            <span className="text-xl font-bold tracking-tight">DataHub Guard AI</span>
          </div>
        </div>
      </header>
      
      <main className="flex-1 max-w-4xl mx-auto px-8 py-16 w-full">
        <h1 className="text-4xl font-bold mb-8">Terms & Conditions</h1>
        <div className="space-y-6 text-slate-300">
          <p>Last updated: July 2026</p>
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-white">1. Introduction</h2>
            <p>Welcome to DataHub Guard AI. These terms govern your use of our autonomous data observability agent.</p>
          </section>
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-white">2. Acceptance of Terms</h2>
            <p>By accessing or using our services, you agree to be bound by these terms. This tool is provided "as-is" for the purpose of the DataHub hackathon.</p>
          </section>
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-white">3. User Responsibilities</h2>
            <p>You are responsible for reviewing and approving all pull requests generated by the AI before merging them into production.</p>
          </section>
        </div>
      </main>
      
      <footer className="py-8 text-center border-t border-white/10 text-slate-500 text-sm">
        <p>Built for the DataHub Agent Hackathon.</p>
      </footer>
    </div>
  );
}
